[package]
name = "code_as_db_models"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
butane = { version = "0.4.2", features=["default", "sqlite", "sqlite-bundled"] }
itertools = "0.10.1"